# Generated by Django 3.2.19 on 2023-07-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20230730_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='branch1',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='district1',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='branch2',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='branch3',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='branch4',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='district2',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='district3',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='district4',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='district5',
        ),
    ]
